In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:

# # إعداد الاتصال بقاعدة البيانات
# # 'mysql+pymysql://user:password@host/database_name'
# engine = create_engine('mysql+pymysql://root:@localhost/anlaysis_sales_datasets')

# # قراءة ملفexcel_file = pd.ExcelFile('Dataset_of_sales.xlsx')
#  الإكسل بالكامل (كل الأوراق)

# for sheet_name in excel_file.sheet_names:
#     # قراءة كل ورقة على حدة
#     df = pd.read_excel(excel_file, sheet_name=sheet_name)
    
#     # رفع البيانات إلى جدول يحمل نفس اسم الورقة
#     # if_exists='replace' سيقوم بإنشاء الجدول أو استبداله إذا كان موجوداً
#     df.to_sql(sheet_name, con=engine, if_exists='replace', index=False)
#     print(f"تم رفع ورقة {sheet_name} بنجاح.")

تم رفع ورقة customers بنجاح.
تم رفع ورقة products بنجاح.
تم رفع ورقة employees بنجاح.
تم رفع ورقة sales بنجاح.

In [59]:
# sheet_name = "customers"
# sheet_name = "products"
# sheet_name = "employees"
sheet_name = "sales"

excel_file = pd.ExcelFile('Dataset_of_sales.xlsx')

df = pd.read_excel(excel_file, sheet_name=sheet_name)

In [60]:
df

,رقم الفاتورة,تاريخ البيع,رقم العميل,اسم العميل,رقم المنتج,اسم المنتج,الكمية,سعر الوحدة,إجمالي قبل الخصم,نسبة الخصم %,مبلغ الخصم,الإجمالي النهائي,رقم الموظف,اسم موظف المبيعات,الفرع,طريقة الدفع,حالة الطلب
0,INV00001,2023-01-02,C025,ريم يوسف علي,P014,سخان كهرباء 50 لتر,3,2800,8400,5,420.0,7980.0,E003,أحمد حسن يوسف,فرع المنصورة,نقدي,مكتمل
1,INV00002,2023-01-10,C016,كريم حسين أحمد,P024,محضر طعام,1,1500,1500,10,150.0,1350.0,E010,نور فاطمة علي,فرع طنطا,تحويل بنكي,تم التسليم
2,INV00003,2023-01-11,C004,عائشة إبراهيم حسن,P013,مكيف هواء 3 حصان,3,16500,49500,15,7425.0,42075.0,E016,رقية يوسف محمد,فرع المنصورة,كارت,تم التسليم
3,INV00004,2023-01-12,C011,إبراهيم حسن عبدالله,P016,سخان غاز 6 لتر,2,1800,3600,0,0.0,3600.0,E011,إبراهيم أحمد حسين,فرع المنيا,نقدي,مكتمل
4,INV00005,2023-01-14,C027,لينا حسن صالح,P014,سخان كهرباء 50 لتر,1,2800,2800,10,280.0,2520.0,E002,فاطمة علي محمود,فرع أسيوط,كارت,مكتمل
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2611,INV02612,2025-08-17,C016,كريم حسين أحمد,P017,سخان غاز 10 لتر,3,2200,6600,10,660.0,5940.0,E016,رقية يوسف محمد,فرع المنصورة,تحويل بنكي,تم التسليم
2612,INV02613,2025-08-17,C030,رامي حسين أحمد,P011,مكيف هواء 1.5 حصان,1,8500,8500,0,0.0,8500.0,E003,أحمد حسن يوسف,فرع المنصورة,تحويل بنكي,تم التسليم
2613,INV02614,2025-08-17,C003,محمد عبدالله أحمد,P023,خلاط كهربائي,2,800,1600,5,80.0,1520.0,E016,رقية يوسف محمد,فرع المنصورة,نقدي,مكتمل
2614,INV02615,2025-08-17,C040,عماد صالح أحمد,P014,سخان كهرباء 50 لتر,1,2800,2800,5,140.0,2660.0,E015,كريم محمود إبراهيم,فرع المنيا,قسط,مكتمل
2615,INV02616,2025-08-17,C027,لينا حسن صالح,P023,خلاط كهربائي,3,800,2400,10,240.0,2160.0,E008,زينب أحمد حسن,فرع الإسكندرية,نقدي,قيد التجهيز

In [61]:
df.info

<bound method DataFrame.info of      رقم الفاتورة تاريخ البيع رقم العميل           اسم العميل رقم المنتج  \
0        INV00001  2023-01-02       C025         ريم يوسف علي       P014
1        INV00002  2023-01-10       C016       كريم حسين أحمد       P024
2        INV00003  2023-01-11       C004    عائشة إبراهيم حسن       P013
3        INV00004  2023-01-12       C011  إبراهيم حسن عبدالله       P016
4        INV00005  2023-01-14       C027        لينا حسن صالح       P014
...           ...         ...        ...                  ...        ...
2611     INV02612  2025-08-17       C016       كريم حسين أحمد       P017
2612     INV02613  2025-08-17       C030       رامي حسين أحمد       P011
2613     INV02614  2025-08-17       C003    محمد عبدالله أحمد       P023
2614     INV02615  2025-08-17       C040       عماد صالح أحمد       P014
2615     INV02616  2025-08-17       C027        لينا حسن صالح       P023

              اسم المنتج  الكمية  سعر الوحدة  إجمالي قبل الخصم  نسبة الخصم %  \
0     سخان كهرباء 50 لتر       3        2800              8400             5
1              محضر طعام       1        1500              1500            10
2       مكيف هواء 3 حصان       3       16500             49500            15
3         سخان غاز 6 لتر       2        1800              3600             0
4     سخان كهرباء 50 لتر       1        2800              2800            10
...                  ...     ...         ...               ...           ...
2611     سخان غاز 10 لتر       3        2200              6600            10
2612  مكيف هواء 1.5 حصان       1        8500              8500             0
2613        خلاط كهربائي       2         800              1600             5
2614  سخان كهرباء 50 لتر       1        2800              2800             5
2615        خلاط كهربائي       3         800              2400            10

      مبلغ الخصم  الإجمالي النهائي رقم الموظف   اسم موظف المبيعات  \
0          420.0            7980.0       E003       أحمد حسن يوسف
1          150.0            1350.0       E010       نور فاطمة علي
2         7425.0           42075.0       E016      رقية يوسف محمد
3            0.0            3600.0       E011   إبراهيم أحمد حسين
4          280.0            2520.0       E002     فاطمة علي محمود
...          ...               ...        ...                 ...
2611       660.0            5940.0       E016      رقية يوسف محمد
2612         0.0            8500.0       E003       أحمد حسن يوسف
2613        80.0            1520.0       E016      رقية يوسف محمد
2614       140.0            2660.0       E015  كريم محمود إبراهيم
2615       240.0            2160.0       E008       زينب أحمد حسن

               الفرع طريقة الدفع   حالة الطلب
0       فرع المنصورة        نقدي        مكتمل
1           فرع طنطا  تحويل بنكي   تم التسليم
2       فرع المنصورة        كارت   تم التسليم
3         فرع المنيا        نقدي        مكتمل
4          فرع أسيوط        كارت        مكتمل
...              ...         ...          ...
2611    فرع المنصورة  تحويل بنكي   تم التسليم
2612    فرع المنصورة  تحويل بنكي   تم التسليم
2613    فرع المنصورة        نقدي        مكتمل
2614      فرع المنيا         قسط        مكتمل
2615  فرع الإسكندرية        نقدي  قيد التجهيز

[2616 rows x 17 columns]>

In [62]:
df.shape

(2616, 17)

In [63]:
df.describe()

,تاريخ البيع,الكمية,سعر الوحدة,إجمالي قبل الخصم,نسبة الخصم %,مبلغ الخصم,الإجمالي النهائي
count,2616,2616.000000,2616.000000,2616.000000,2616.000000,2616.000000,2616.000000
mean,2024-09-02 06:30:49.541284352,2.005734,6744.587156,13525.168196,4.245031,606.233180,12918.935015
min,2023-01-02 00:00:00,1.000000,380.000000,380.000000,0.000000,0.000000,323.000000
25%,2024-03-23 00:00:00,1.000000,1500.000000,2500.000000,0.000000,0.000000,2400.000000
50%,2024-10-02 00:00:00,2.000000,3500.000000,7500.000000,0.000000,0.000000,7200.000000
75%,2025-03-17 00:00:00,3.000000,12000.000000,19600.000000,10.000000,525.000000,18500.000000
max,2025-08-17 00:00:00,3.000000,22000.000000,66000.000000,15.000000,9900.000000,66000.000000
std,NaN,0.813583,6236.660336,14647.034301,5.513201,1330.616809,13990.788304

In [64]:
df.isnull().sum()

رقم الفاتورة         0
تاريخ البيع          0
رقم العميل           0
اسم العميل           0
رقم المنتج           0
اسم المنتج           0
الكمية               0
سعر الوحدة           0
إجمالي قبل الخصم     0
نسبة الخصم %         0
مبلغ الخصم           0
الإجمالي النهائي     0
رقم الموظف           0
اسم موظف المبيعات    0
الفرع                0
طريقة الدفع          0
حالة الطلب           0
dtype: int64

In [65]:
df.duplicated().sum()

np.int64(0)

In [66]:
df.dtypes

رقم الفاتورة                 object
تاريخ البيع          datetime64[ns]
رقم العميل                   object
اسم العميل                   object
رقم المنتج                   object
اسم المنتج                   object
الكمية                        int64
سعر الوحدة                    int64
إجمالي قبل الخصم              int64
نسبة الخصم %                  int64
مبلغ الخصم                  float64
الإجمالي النهائي            float64
رقم الموظف                   object
اسم موظف المبيعات            object
الفرع                        object
طريقة الدفع                  object
حالة الطلب                   object
dtype: object

In [67]:
df.columns = df.columns.str.replace(" " ,"_")

In [68]:
df.columns.tolist()

['رقم_الفاتورة',
 'تاريخ_البيع',
 'رقم_العميل',
 'اسم_العميل',
 'رقم_المنتج',
 'اسم_المنتج',
 'الكمية',
 'سعر_الوحدة',
 'إجمالي_قبل_الخصم',
 'نسبة_الخصم_%',
 'مبلغ_الخصم',
 'الإجمالي_النهائي',
 'رقم_الموظف',
 'اسم_موظف_المبيعات',
 'الفرع',
 'طريقة_الدفع',
 'حالة_الطلب']

In [69]:

# إعداد الاتصال بقاعدة البيانات
# 'mysql+pymysql://user:password@host/database_name'
engine = create_engine('mysql+pymysql://root:@localhost/anlaysis_sales_datasets')

# رفع البيانات إلى جدول يحمل نفس اسم الورقة
# if_exists='replace' سيقوم بإنشاء الجدول أو استبداله إذا كان موجوداً
df.to_sql(sheet_name, con=engine, if_exists='replace', index=False)
print(f"تم رفع ورقة {sheet_name} بنجاح.")

تم رفع ورقة sales بنجاح.